Data saving
xebuk/Faerie pull request #36
Opened 2024-10-04 09:47 UTC by xebuk

2024-10-04 12:10 UTC, LartsAL requested changes

2024-10-04 12:10 UTC, LartsAL commented on src/main/java/game/entities/PlayerCharacter.java
> +    public void setAttackPower() {
Де-факто, это не сеттеры, а инициализаторы для начальных значений. Переименовать в init[VariableName]

2024-10-04 13:46 UTC, xebuk commented on src/main/java/game/entities/PlayerCharacter.java
> +    public void setAttackPower() {
Сделано

2024-10-06 12:46 UTC, LartsAL approved these changes

2024-10-06 12:46 UTC, LartsAL commented on src/main/java/botexecution/AbilBot.java
> +    public Ability createPc() {
Назови createPlayerCharacter, мы не на C пишем, у нас функции с названиями больше трёх букв компилируются

2024-10-06 12:46 UTC, LartsAL commented on src/main/java/botexecution/AbilBot.java
> +                .info("creates a pc")
Аналогично, рандомный пользователь не сразу поймёт, что есть pc

2024-10-06 12:46 UTC, LartsAL commented on src/main/java/botexecution/AbilBot.java
> +        if (currentUser.creationOfPc && update.hasCallbackQuery() && Objects.equals(currentUser.getChatId(), getChatId(update))) {
Pc -> PlayerCharacter

2024-10-06 12:46 UTC, LartsAL commented on src/main/java/botexecution/ChatSession.java
> +    private final Long chatId;
Зачем использовать класс, если есть примитивный long?

2024-10-06 12:46 UTC, LartsAL commented on src/main/java/game/entities/PlayerCharacter.java
> +        return (-5 + (stat / 2));
Магические числа или почему -5?

2024-10-06 13:32 UTC, xebuk commented on src/main/java/botexecution/AbilBot.java
> +    public Ability createPc() {
Сделано

2024-10-06 13:35 UTC, xebuk commented on src/main/java/botexecution/AbilBot.java
> +                .info("creates a pc")
Сделано

2024-10-06 13:35 UTC, xebuk commented on src/main/java/botexecution/AbilBot.java
> +        if (currentUser.creationOfPc && update.hasCallbackQuery() && Objects.equals(currentUser.getChatId(), getChatId(update))) {
Сделано

2024-10-06 13:36 UTC, xebuk commented on src/main/java/botexecution/ChatSession.java
> +    private final Long chatId;
пока писал, автоматически написал, поменял

2024-10-06 13:37 UTC, xebuk commented on src/main/java/game/entities/PlayerCharacter.java
> +        return (-5 + (stat / 2));
формула расчета модификатора. Смотри статью про статы на DnD.su, я просто подметил такую закономерность и решил написать кратко

2024-10-06 13:38 UTC, merged